### ISSUE TITLE
Unable to create an account

### ISSUE THREAD

**Issue by navelpluisje** [bolt/marketplace-site#13]
While trying to setup an account you will be returned to the register view. All the fields are cleared and there is no kind of feedback like an error message.

**Comment by bobdenotter** [comment]
Hi, this should be fixed now! Could you try again?

**Comment by navelpluisje** [comment]
Creating the account works now. Getting a message my username already exists. Made it probably a while ago. So I created a new one. 
But.....
I got the message that I could login, but after trying to login I get the message that the login had been unsuccessful.
I also didn't get a mail notification.

**Comment by GawainLynch** [comment]
Closing :wave:
