### ISSUE TITLE
Json search not working

### ISSUE THREAD

**Issue by PhillippOhlandt** [bolt/marketplace-site#46]
On the new extension store site, the json search is broken:
https://dev.extensions.bolt.cm/search.json?order=date&type=bolt-theme

When it's working again, there are two more things:

- Created_at value
- User nickname

I can handle the nickname on boltthem.es if that's too much work to get it in again.

**Comment by PhillippOhlandt** [comment]
@GawainLynch the `updated` value is null. It seems like I did a typo above because I meant the `updated` value.

**Comment by GawainLynch** [comment]
Cleaned that whole SELECT up now and GTG.
