### ISSUE TITLE
[RFC] Filter extensions by favorites

### ISSUE THREAD

**Issue by nbehier** [bolt/marketplace-site#57]
On page `https://extensions.bolt.cm/`, when I'm logged in, I could mark my favorites extensions. But when I'm logged in, I didn't find any page with all my favorites extensions. It would be nice to have such a page. (Try url like `https://extensions.bolt.cm/star/list` or `https://extensions.bolt.cm/stars` but get error pages).

**Comment by GawainLynch** [comment]
> Try url like https://extensions.bolt.cm/star/list [snip] but get error pages

Updated the handling of that route to be a little less hostile. Its current use is just the addition of the stars

**Comment by GawainLynch** [comment]
So, @nbehier are you feeling the BoltLove today?

https://extensions.bolt.cm/profile/starred :wink:

**Comment by nbehier** [comment]
Bolt creators and community are awesome! Really! Love you guys!
